{% set name = "gstlal-ugly" %}
{% set version = "1.6.3" %}
{% set sha256 = "231e26aee3c70f328a33c688588fd16081b56e1ad3b5c511bee2e37f92fb7048" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - fftw
    - glib
    - gsl
    - gstreamer 1.14.4
    - gst-orc >=0.4
    - gst-plugins-base
    - gst-python
    - gstlal >=1.5.0
    - lal >=6.19.0
    - lalmetaio >=1.5.0
    - ldas-tools-framecpp >=2.6.2
    - pygobject >=3.14
    - python 2.7
    - python-lal
    - python-ligo-lw >=1.2.0
    - lscsoft-glue >=1.59.3
  run:
    - fftw
    - gsl
    - {{ pin_compatible('gstreamer') }}
    - gst-orc >=0.4
    - gst-plugins-base
    - gst-python
    - gstlal >=1.5.0
    - h5py
    - lal >=6.19.2
    - lalmetaio >=1.5.0
    - lalapps >=6.23.0
    - ligo-segments >=1.0.0
    - lscsoft-glue >=1.59.3
    - ldas-tools-framecpp >=2.6.2
    - matplotlib-base
    - numpy
    - scipy
    - pygobject >=3.14
    - python 2.7
    - python-lal
    - python-lalsimulation
    - python-ligo-lw >=1.2.0

test:
  imports:
    - gstlal
    - gstlal.aggregator
    - gstlal.metric
    - gstlal.tree
  commands:
    # check executables
    - gstlal_condor_top --help
    - gstlal_dag_run_time --help
    - gstlal_get_online_coinc_times --help
    - gstlal_glitch_population --help
    - gstlal_harmonic_mean_psd --help
    - gstlal_kafka_dag --help
    - gstlal_ligolw_add_without_reassign --help
    - gstlal_median_of_psds --help
    - gstlal_reduce_dag --help
    - gstlal_segments_operations --help
    - gstlal_segments_trim --help
    - gstlal_svd_bank_checkerboard --help

about:
  home: https://wiki.ligo.org/Computing/DASWG/GstLAL
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://docs.ligo.org/lscsoft/gstlal/{{ name }}/{{ name }}.html
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: gstlal-ugly
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - myNameIsPatrick
